# Generated by Django 3.2.7 on 2021-09-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-updated_at']},
        ),
    ]
