# Generated by Django 3.2.7 on 2021-09-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210923_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('project', 'name')},
        ),
    ]
