# Generated by Django 3.2.7 on 2021-09-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210923_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-updated_at']},
        ),
    ]
