# Generated by Django 3.2.7 on 2021-09-26 13:49

import apps.project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=20, validators=[apps.project.validators.validate_hex_value]),
        ),
    ]
