# Generated by Django 3.2.7 on 2022-01-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('value', models.BigIntegerField()),
                ('min_val', models.BigIntegerField(null=True)),
                ('max_val', models.BigIntegerField(null=True)),
                ('units', models.CharField(max_length=10, null=True)),
                ('scale', models.FloatField(null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.field')),
            ],
        ),
    ]
