# Generated by Django 3.2.7 on 2022-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_fieldchoice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldchoice',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='max_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='min_val',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='units',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
