# Generated by Django 3.2.7 on 2022-01-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_field_unit_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='unit_scale',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='unit_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
