# Generated by Django 3.2.7 on 2022-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20220104_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldchoice',
            name='max_val',
        ),
        migrations.RemoveField(
            model_name='fieldchoice',
            name='min_val',
        ),
        migrations.RemoveField(
            model_name='fieldchoice',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='fieldchoice',
            name='units',
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='field',
            name='value_max',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='value_min',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
