# Generated by Django 3.2.7 on 2022-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20220104_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('INT', 'Signed Integer'), ('UINT', 'Unsigned Integer'), ('ASCII', 'Text'), ('RES', 'Reserved'), ('FLAG_AH', 'Flag, Active High'), ('FLAG_AL', 'Flag, Active Low'), ('DOUBLE', 'Double Floating Point'), ('MUX', 'Multiplex')], default='RES', max_length=10),
        ),
    ]
