# Generated by Django 3.2.7 on 2022-02-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_field_type'),
        ('project', '0016_auto_20220129_1229'),
    ]

    operations = [
    ]
