# Generated by Django 3.2.7 on 2022-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_merge_0016_alter_field_type_0016_auto_20220129_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='access',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='default',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('INT', 'Signed Integer'), ('UINT', 'Unsigned Integer'), ('ASCII', 'Text'), ('RES', 'Reserved'), ('FLAG_AH', 'Flag, Active High'), ('FLAG_AL', 'Flag, Active Low'), ('DOUBLE', 'Double Floating Point'), ('MUX', 'Multiplex')], default='UINT', max_length=10),
        ),
    ]
