# Generated by Django 3.2.7 on 2022-02-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20220208_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('version', 'address'), ('version', 'name')},
        ),
    ]
